//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherReport_cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class 北京市
    {
        public string 日期 { get; set; }
        public string 省份 { get; set; }
        public string 城市 { get; set; }
        public string 天气类型 { get; set; }
        public string 温度 { get; set; }
        public string 风向 { get; set; }
        public string 风力 { get; set; }
        public string 湿度 { get; set; }
        public string 空气质量 { get; set; }
        public int seq { get; set; }
    }
}
